# For more information: https://laravel.com/docs/sail
version: '3'
services:
    cookfun:
        container_name: cookfun
        build:
            context: .
            dockerfile: Dockerfile
            target: final
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${LARAVEL_WEBSOCKETS_PORT:-6001}:6001'
        working_dir: /var/www
        restart: unless-stopped
        volumes:
            - ./:/var/www
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
            - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
        networks:
            - sail
        depends_on:
            - mysql
            - redis
    #webserver
    cookserver:
        image: nginx:alpine
        container_name: cookserver
        restart: unless-stopped
        networks:
            - sail
        ports:
            - '${APP_PORT:-80}:80'
        volumes:
            - ./:/var/www
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        links:
            - cookfun
    mysql:
        image: 'mariadb:latest'
        ports:
            - 3307:3306
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "${DB_HOST}"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - sail-mysql:/var/lib/mysql
            - ./database/dumps:/backups
        networks:
            - sail
        restart: unless-stopped
        command: --sort_buffer_size=20M
    redis:
        image: 'redis:alpine'
        container_name: redis-webshop
        ports:
            - '6380:6379'
        volumes:
            - ./:/var/www
        networks:
            - sail
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s
    mailhog:
        image: mailhog/mailhog:latest
        container_name: mailhog-cook
        ports:
            - "${MAIL_PORT:-1025}:1025"
            - "${MAILHOG_DASHBOARD_PORT:-8100}:8025"
        networks:
            - sail

networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local